import { SponsorItem, StreamState } from "@/lib/types";

export const DEFAULT_SPONSORS: SponsorItem[] = [
  {
    id: "sponsor-1",
    brand: "NOTHING",
    subtitle: "AUDIO & MOBILE COLLABORATION",
    badge: "OFFICIAL AUDIO PARTNER",
    headline: "Pure Sound. Transparent Design.",
    description: "Experience the ear (2) with high-res audio and smart ANC.",
    code: "UNCOMPILED",
    discount: "15% OFF AT CHECKOUT",
    url: "nothing.tech/uncompiled",
    accentColor: "#ffffff",
    logoText: "NOTHING (R)",
  },
  {
    id: "sponsor-2",
    brand: "KEYCHRON",
    subtitle: "PREMIUM CUSTOM HARDWARE",
    badge: "DESK SETUP SPONSOR",
    headline: "Crafted For Ultimate Precision.",
    description: "Wireless mechanical keyboards with hot-swappable switches and CNC aluminum body.",
    code: "OMSTREAM",
    discount: "$20 OFF KEYBOARDS",
    url: "keychron.com/uncompiled",
    accentColor: "#f59e0b",
    logoText: "KEYCHRON LABS",
  },
  {
    id: "sponsor-3",
    brand: "MOFT",
    subtitle: "MOBILE ECOSYSTEM & STANDS",
    badge: "LIFESTYLE GEAR",
    headline: "Invisible Workstation Anywhere.",
    description: "Snap-on magnetic stands, origami laptop desks, and creator essentials.",
    code: "UNCOMPILED10",
    discount: "10% OFF SITEWIDE",
    url: "moft.us/uncompiled",
    accentColor: "#38bdf8",
    logoText: "MOFT DESIGN",
  },
  {
    id: "sponsor-4",
    brand: "TEENAGE TECH",
    subtitle: "MODULAR SYNTHESIZERS & GEAR",
    badge: "AUDIO ENGINEERING",
    headline: "Tactile Instruments For Modern Makers.",
    description: "High-precision pocket sound generators and minimalist audio devices.",
    code: "UNCOMPILED25",
    discount: "STUDIO BUNDLE ACCESS",
    url: "teenage.engineering",
    accentColor: "#ff5252",
    logoText: "TE // 01",
  },
];

export const INITIAL_STREAM_STATE: StreamState = {
  currentScene: "game",
  isLive: true,
  isMicMuted: false,
  isAudioMuted: false,
  privacyShield: false,
  topic: "EDITORIAL DESIGN & STREAMING SUITE ARCHITECTURE // UNCUT",
  streamTitle: "UNCOMPILED.OM // LIVE LAB SESSION",
  tickerText: "YOUTUBE: @uncompiled.om • DISCORD.GG/UNCOMPILED • X: @uncompiled_om • LIVE IN 1080P60 HDR",
  followerGoal: {
    current: 842,
    target: 1000,
    label: "COMMUNITY FOLLOWER GOAL",
  },
  subGoal: {
    current: 47,
    target: 100,
    label: "STUDIO SUB GOAL",
  },
  activeSponsorId: null,
  timerSeconds: 300,
  textAnimation: "blur-focus",
  webcamConfig: {
    mode: "separated",
    aspectRatio: "16:9",
    label: "OM.CAM // STUDIO",
    sublabel: "uncompiled.om",
    micLabel: "SHURE SM7B",
    borderGlow: true,
    rounding: "xl",
    privacyBlur: false,
    voiceReactive: true,
  },
  latestSub: "alex_prime",
  topDonation: "elena.eth ($50.00)",
  latestFollower: "marcus_dev",
};
